### ISSUE TITLE
Custom command for setting a node's zone info through `-Cnode.attr.zone=`

### ISSUE THREAD

**Issue by chaudum** [crate/crate-operator#124]
As of now, a node's zone information is set automatically in case the `CLOUD_PROVIDER` setting is set to `aws` or `azure`. In this case, the `crate` entrypoint command is extended with `-Cnode.attr.zone=`

https://github.com/crate/crate-operator/blob/ff02f87f1f7aa5e22449de4bf88de6b564e493e4/crate/operator/create.py#L396-L401

These two settings work for EKS on AWS and AKS on Azure, however there can be other setups of Kubernetes as well, such as self-managed setups on different cloud providers. In these cases, one wants to provide a custom command that provides the value for the zone attribute.

Instead of providing a custom command for the `zone` node attribute, the operator configuration could provide a generic map of attribute->value for the crate command. The value could either be a fixed value or a command that is executed upon startup.

**Comment by MarkusH** [comment]
I understand that the current implementation doesn't natively support eg. GCP or so, but one can already set `.spec.cluster.settings` which provides a way to pass arguments to CrateDB. So, something like this should already work:
```yaml
apiVersion: cloud.crate.io/v1
kind: CrateDB
metadata:
  name: my-cluster
  namespace: my-namespace
  cluster:
    imageRegistry: crate
    name: my-cluster
    version: 4.3.1
    settings:
      - -Cnode.attr.zone=$(curl -s 'https://example.com')
  nodes:
    data:
    - name: t1
      replicas: 1
      resources:
        cpus: 0.25
        memory: 512Mi
        heapRatio: 0.25
        disk:
          storageClass: default
          size: 8GiB
          count: 1

```
