### ISSUE TITLE
Not enough permissions to watch for resources

### ISSUE THREAD

**Issue by remear** [crate/crate-operator#459]
Installing and running the operator presents a permissions warning in the logs.

```
kopf._core.reactor.o [WARNING ] Not enough permissions to watch for resources: changes (creation/deletion/updates) will not be noticed; the resources are only refreshed on operator restarts.
```

The warning goes away when adding the following RBAC permissions, as mentioned in https://github.com/nolar/kopf/issues/901.

```yaml
- apiGroups: [apiextensions.k8s.io]
  resources: [customresourcedefinitions]
  verbs: [list, watch]
- apiGroups: [""]
  resources: [namespaces]
  verbs: [list, watch]
```

I'm assuming  the desired behavior is for the operator to have the ability to watch for and react to changes and not require a restart. If that's not the case, it looks like this can be disabled in kopf via `settings.scanning.disabled = True`.

I'd be happy to work on a PR for whichever path is desired.
