### ISSUE TITLE
Only 1 node started when 5 requested

### ISSUE THREAD

**Issue by robd003** [crate/crate-operator#498]
I tried deploying a 5 node cluster, but only 1 node is being started.

```
apiVersion: cloud.crate.io/v1
kind: CrateDB
spec:
  cluster:
    imageRegistry: crate
    name: crate-dev
    version: 5.2.5
  nodes:
    data:
      - name: crate-cluster
        replicas: 5
        resources:
          disk:
            count: 1
            size: 128GiB
            storageClass: ebs-storage-class
          heapRatio: 0.25
          limits:
            cpu: 1
            memory: 15Gi
```
