### ISSUE TITLE
Add configuration option for Crate deployment to specify if internal-only or internet facing

### ISSUE THREAD

**Issue by robd003** [crate/crate-operator#510]
If the `CLOUD_PROVIDER` parameter is set to `aws` I'd like to be able to define whether the Crate deployment should be internal only or internet accessible. At the moment every time Crate is deployed it only creates an internet accessible loadbalancer. I'd like the ability to restrict traffic to my internal cluster only.

Example service annotation for internal-only LB:

```
kind: Service
metadata:
  name: crate-service
  namespace: crate
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internal
spec:
  ports:
    - port: 4200
      targetPort: 4200
      protocol: TCP
    - port: 5432
      targetPort: 5432
      protocol: TCP
  type: LoadBalancer
```

**Comment by SStorm** [comment]
Hi @robd003,

this is already possible by specifying additional service annotations when creating the CrateDB CRD:

```yaml
apiVersion: cloud.crate.io/v1
kind: CrateDB
metadata:
  name: my-cluster
  namespace: dev
spec:
  cluster:
    imageRegistry: crate
    name: crate-dev
    version: 5.2.5
    service:
        annotations:
            service.beta.kubernetes.io/aws-load-balancer-scheme: internal
  nodes:
    data:
    - name: hot
      replicas: 3
      resources:
        limits:
          cpu: 4
          memory: 4Gi
        disk:
          count: 1
          size: 128GiB
          storageClass: default
        heapRatio: 0.5
```

Although I appreciate it's not documented well (or at all).
