### ISSUE TITLE
Override Clusters Settings from the operator configuration

### ISSUE THREAD

**Issue by etiennejournet** [crate/crate-operator#515]
Hello ! 

Following [this](https://github.com/crate/crate-operator/issues/514), I was wondering if it's possible to override settings in all clusters from the operator configuration.

The use case of this previous issue would be to set "network.host" once and for all in the operator configuration, and have it set all the way to the Cluster Nodes.
We could set this variable (and others) from the values.yaml in helm. An example: 
```
cluster_overrides:
  - crate-arguments:
    - network.host=0.0.0.0
  - spec:
    - image_repository: <custom_image> ## Also useful to force the repository
    - storage_class: <forced_storage_class> ## Force the storage class through the cluster
```

Regards,
